### ISSUE TITLE
Enable pgvector Support for PostgreSQL

### ISSUE THREAD

**Issue by brylie** [brylie/wagtail-pgvector-template#1]
Description
We need to enable pgvector support for the PostgreSQL database in our development container setup. pgvector is essential for handling vector operations, which are critical for our application's functionality. Here are the proposed steps to achieve this:

1. **Initial Attempt: Use pgvector/pgvector Image**
   - Replace the current `postgres:latest` image with `pgvector/pgvector` from Dockerhub in the `docker-compose.yml` file.

2. **Alternative Approach: Extend PostgreSQL Image**
   - If the initial attempt does not work as expected, we will create a custom Dockerfile for the PostgreSQL service.
   - The custom Dockerfile will extend an existing PostgreSQL image and enable the pgvector extension.

## Proposed Changes

1. **Modify `docker-compose.yml`:**
   - Change the `image` field for the `db` service to `pgvector/pgvector`.

2. **Create a Custom Dockerfile for PostgreSQL (if needed):**
   - If using the `pgvector/pgvector` image is not feasible, create a `Dockerfile` for the PostgreSQL service.
   - Extend the existing PostgreSQL image and install pgvector.

## Acceptance Criteria
- PostgreSQL service in the development container has pgvector enabled.
- Application can successfully use pgvector for vector operations.

## Example Configuration

**Option 1: Using pgvector/pgvector Image**

```yaml
services:
  db:
    image: pgvector/pgvector:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
```

**Option 2: Extending PostgreSQL Image**

Create a `Dockerfile` for PostgreSQL:

```dockerfile
# Use the official PostgreSQL image as the base
FROM postgres:latest

# Install pgvector extension
RUN apt-get update && apt-get install -y \
    postgresql-server-dev-all \
    && git clone https://github.com/pgvector/pgvector.git \
    && cd pgvector && make && make install \
    && rm -rf /var/lib/apt/lists/*

# Set the default command to run PostgreSQL
CMD ["postgres"]
```

Update `docker-compose.yml` to use the custom Dockerfile:

```yaml
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
```
